import json
import os
import pathlib
import re
import shlex
import subprocess
import tempfile
import unittest

ROOT = pathlib.Path(__file__).resolve().parents[1]
EXPECTED = {'version': 4,
 'find': 7,
 'delegate': 8,
 'query': 9,
 'revoke': 10,
 'no_space': -7,
 'timeout': -8,
 'wait_max_ticks': 1000,
 'sleep': 11,
 'recv_wait': 12,
 'delegate_right': 2147483648,
 'operation_max': 16,
 'operation_rights': 65535,
 'instance_tag': 64,
 'control_tag': 80,
 'domain_tag': 96,
 'host_query_right': 1,
 'host_stop_right': 2,
 'host_reap_right': 4,
 'create': 13,
 'status': 14,
 'stop': 15,
 'reap': 16,
 'rebind': 17,
 'creation_revoke': 18,
 'domain_status': 19,
 'file_read_right': 4,
 'cap_ack_right': 32,
 'block_read_right': 64,
 'block_write_right': 128,
 'block_reply_right': 256,
 'file_open_right': 512,
 'file_chunk_read_right': 1024,
 'file_write_right': 2048,
 'file_close_right': 4096,
 'file_result_right': 8192,
 'hosting_request_right': 16384,
 'hosting_reply_right': 32768,
 'role_block': 0,
 'role_filesystem': 1,
 'role_client': 2,
 'role_probe': 3,
 'role_supervisor': 4,
 'role_worker': 5,
 'message_size': 48,
 'message_align': 8,
 'message_sender': 0,
 'message_operation': 8,
 'message_length': 12,
 'message_payload': 16,
 'boot_size': 80,
 'boot_align': 8,
 'boot_abi': 0,
 'boot_role': 4,
 'boot_generation': 8,
 'boot_scenario': 16,
 'boot_endpoint': 24,
 'boot_parent_endpoint': 32,
 'boot_instance': 40,
 'boot_creation': 48,
 'boot_parent_channel': 56,
 'boot_template_id': 64,
 'boot_depth': 68,
 'boot_identity': 72,
 'boot_reserved': 76,
 'request_size': 24,
 'request_align': 8,
 'request_parent': 0,
 'request_holder': 8,
 'request_rights': 16,
 'request_reserved': 20,
 'info_size': 32,
 'info_align': 8,
 'info_holder': 0,
 'info_target': 8,
 'info_rights': 16,
 'info_reserved': 20,
 'info_parent': 24,
 'create_request_size': 32,
 'create_request_align': 8,
 'create_request_authority': 0,
 'create_request_request': 8,
 'create_request_template_id': 16,
 'create_request_descendant_slots': 20,
 'create_request_descendant_pages': 24,
 'create_request_reserved': 28,
 'create_result_size': 48,
 'create_result_align': 8,
 'create_result_instance': 0,
 'create_result_control': 8,
 'create_result_endpoint': 16,
 'create_result_channel': 24,
 'create_result_creation': 32,
 'create_result_slot': 40,
 'create_result_identity': 44,
 'rebind_request_size': 32,
 'rebind_request_align': 8,
 'rebind_request_authority': 0,
 'rebind_request_control': 8,
 'rebind_request_request': 16,
 'rebind_request_reserved': 24,
 'cell_status_size': 104,
 'cell_status_align': 8,
 'cell_status_instance': 0,
 'cell_status_control': 8,
 'cell_status_endpoint': 16,
 'cell_status_domain': 24,
 'cell_status_parent_instance': 32,
 'cell_status_parent_endpoint': 40,
 'cell_status_generation': 48,
 'cell_status_slot': 56,
 'cell_status_template_id': 60,
 'cell_status_depth': 64,
 'cell_status_phase': 68,
 'cell_status_faults': 72,
 'cell_status_restarts': 76,
 'cell_status_reason': 80,
 'cell_status_own_pages': 84,
 'cell_status_reserved_slots': 88,
 'cell_status_reserved_pages': 92,
 'cell_status_available_slots': 96,
 'cell_status_available_pages': 100,
 'domain_status_size': 72,
 'domain_status_align': 8,
 'domain_status_domain': 0,
 'domain_status_holder': 8,
 'domain_status_instance': 16,
 'domain_status_slot_limit': 24,
 'domain_status_page_limit': 28,
 'domain_status_owned_slots': 32,
 'domain_status_owned_pages': 36,
 'domain_status_reserved_slots': 40,
 'domain_status_reserved_pages': 44,
 'domain_status_available_slots': 48,
 'domain_status_available_pages': 52,
 'domain_status_max_depth': 56,
 'domain_status_template_mask': 60,
 'domain_status_recipe': 64,
 'domain_status_revoked': 68}
C_SOURCE = r'''
#include <stddef.h>
#include <stdio.h>
#include <zeal/abi.h>
#include <zeal/hosting_policy.h>
int main(void) {
  printf("{\"version\":%lld,\"find\":%lld,\"delegate\":%lld,\"query\":%lld,\"revoke\":%lld,\"no_space\":%lld,\"timeout\":%lld,\"wait_max_ticks\":%lld,\"sleep\":%lld,\"recv_wait\":%lld,\"delegate_right\":%lld,\"operation_max\":%lld,\"operation_rights\":%lld,\"instance_tag\":%lld,\"control_tag\":%lld,\"domain_tag\":%lld,\"host_query_right\":%lld,\"host_stop_right\":%lld,\"host_reap_right\":%lld,\"create\":%lld,\"status\":%lld,\"stop\":%lld,\"reap\":%lld,\"rebind\":%lld,\"creation_revoke\":%lld,\"domain_status\":%lld,\"file_read_right\":%lld,\"cap_ack_right\":%lld,\"block_read_right\":%lld,\"block_write_right\":%lld,\"block_reply_right\":%lld,\"file_open_right\":%lld,\"file_chunk_read_right\":%lld,\"file_write_right\":%lld,\"file_close_right\":%lld,\"file_result_right\":%lld,\"hosting_request_right\":%lld,\"hosting_reply_right\":%lld,\"role_block\":%lld,\"role_filesystem\":%lld,\"role_client\":%lld,\"role_probe\":%lld,\"role_supervisor\":%lld,\"role_worker\":%lld,\"message_size\":%lld,\"message_align\":%lld,\"message_sender\":%lld,\"message_operation\":%lld,\"message_length\":%lld,\"message_payload\":%lld,\"boot_size\":%lld,\"boot_align\":%lld,\"boot_abi\":%lld,\"boot_role\":%lld,\"boot_generation\":%lld,\"boot_scenario\":%lld,\"boot_endpoint\":%lld,\"boot_parent_endpoint\":%lld,\"boot_instance\":%lld,\"boot_creation\":%lld,\"boot_parent_channel\":%lld,\"boot_template_id\":%lld,\"boot_depth\":%lld,\"boot_identity\":%lld,\"boot_reserved\":%lld,\"request_size\":%lld,\"request_align\":%lld,\"request_parent\":%lld,\"request_holder\":%lld,\"request_rights\":%lld,\"request_reserved\":%lld,\"info_size\":%lld,\"info_align\":%lld,\"info_holder\":%lld,\"info_target\":%lld,\"info_rights\":%lld,\"info_reserved\":%lld,\"info_parent\":%lld,\"create_request_size\":%lld,\"create_request_align\":%lld,\"create_request_authority\":%lld,\"create_request_request\":%lld,\"create_request_template_id\":%lld,\"create_request_descendant_slots\":%lld,\"create_request_descendant_pages\":%lld,\"create_request_reserved\":%lld,\"create_result_size\":%lld,\"create_result_align\":%lld,\"create_result_instance\":%lld,\"create_result_control\":%lld,\"create_result_endpoint\":%lld,\"create_result_channel\":%lld,\"create_result_creation\":%lld,\"create_result_slot\":%lld,\"create_result_identity\":%lld,\"rebind_request_size\":%lld,\"rebind_request_align\":%lld,\"rebind_request_authority\":%lld,\"rebind_request_control\":%lld,\"rebind_request_request\":%lld,\"rebind_request_reserved\":%lld,\"cell_status_size\":%lld,\"cell_status_align\":%lld,\"cell_status_instance\":%lld,\"cell_status_control\":%lld,\"cell_status_endpoint\":%lld,\"cell_status_domain\":%lld,\"cell_status_parent_instance\":%lld,\"cell_status_parent_endpoint\":%lld,\"cell_status_generation\":%lld,\"cell_status_slot\":%lld,\"cell_status_template_id\":%lld,\"cell_status_depth\":%lld,\"cell_status_phase\":%lld,\"cell_status_faults\":%lld,\"cell_status_restarts\":%lld,\"cell_status_reason\":%lld,\"cell_status_own_pages\":%lld,\"cell_status_reserved_slots\":%lld,\"cell_status_reserved_pages\":%lld,\"cell_status_available_slots\":%lld,\"cell_status_available_pages\":%lld,\"domain_status_size\":%lld,\"domain_status_align\":%lld,\"domain_status_domain\":%lld,\"domain_status_holder\":%lld,\"domain_status_instance\":%lld,\"domain_status_slot_limit\":%lld,\"domain_status_page_limit\":%lld,\"domain_status_owned_slots\":%lld,\"domain_status_owned_pages\":%lld,\"domain_status_reserved_slots\":%lld,\"domain_status_reserved_pages\":%lld,\"domain_status_available_slots\":%lld,\"domain_status_available_pages\":%lld,\"domain_status_max_depth\":%lld,\"domain_status_template_mask\":%lld,\"domain_status_recipe\":%lld,\"domain_status_revoked\":%lld}\n",
      (long long)(Z_ABI_VERSION),
      (long long)(Z_CAP_FIND),
      (long long)(Z_CAP_DELEGATE),
      (long long)(Z_CAP_QUERY),
      (long long)(Z_CAP_REVOKE),
      (long long)(Z_NO_SPACE),
      (long long)(Z_TIMEOUT),
      (long long)(Z_WAIT_MAX_TICKS),
      (long long)(Z_SLEEP),
      (long long)(Z_RECV_WAIT),
      (long long)(Z_RIGHT_DELEGATE),
      (long long)(Z_HOST_REPLY),
      (long long)(Z_RIGHT_OPERATIONS),
      (long long)(Z_HOST_INSTANCE_TAG),
      (long long)(Z_HOST_CONTROL_TAG),
      (long long)(Z_HOST_DOMAIN_TAG),
      (long long)(Z_HOST_QUERY),
      (long long)(Z_HOST_STOP),
      (long long)(Z_HOST_REAP),
      (long long)(Z_CREATE),
      (long long)(Z_CELL_STATUS),
      (long long)(Z_CELL_STOP),
      (long long)(Z_CELL_REAP),
      (long long)(Z_CELL_REBIND),
      (long long)(Z_CREATION_REVOKE),
      (long long)(Z_DOMAIN_STATUS),
      (long long)(Z_RIGHT(Z_FILE_READ)),
      (long long)(Z_RIGHT(Z_CAP_ACK)),
      (long long)(Z_RIGHT(Z_BLOCK_READ)),
      (long long)(Z_RIGHT(Z_BLOCK_WRITE)),
      (long long)(Z_RIGHT(Z_BLOCK_REPLY)),
      (long long)(Z_RIGHT(Z_FILE_OPEN)),
      (long long)(Z_RIGHT(Z_FILE_CHUNK_READ)),
      (long long)(Z_RIGHT(Z_FILE_WRITE)),
      (long long)(Z_RIGHT(Z_FILE_CLOSE)),
      (long long)(Z_RIGHT(Z_FILE_RESULT)),
      (long long)(Z_RIGHT(Z_HOST_REQUEST)),
      (long long)(Z_RIGHT(Z_HOST_REPLY)),
      (long long)(Z_BLOCK),
      (long long)(Z_FS),
      (long long)(Z_CLIENT),
      (long long)(Z_PROBE),
      (long long)(Z_SUPERVISOR),
      (long long)(Z_WORKER),
      (long long)(sizeof(struct z_message)),
      (long long)(_Alignof(struct z_message)),
      (long long)(offsetof(struct z_message, sender)),
      (long long)(offsetof(struct z_message, operation)),
      (long long)(offsetof(struct z_message, length)),
      (long long)(offsetof(struct z_message, payload)),
      (long long)(sizeof(struct z_boot_info)),
      (long long)(_Alignof(struct z_boot_info)),
      (long long)(offsetof(struct z_boot_info, abi)),
      (long long)(offsetof(struct z_boot_info, role)),
      (long long)(offsetof(struct z_boot_info, generation)),
      (long long)(offsetof(struct z_boot_info, scenario)),
      (long long)(offsetof(struct z_boot_info, endpoint)),
      (long long)(offsetof(struct z_boot_info, parent_endpoint)),
      (long long)(offsetof(struct z_boot_info, instance)),
      (long long)(offsetof(struct z_boot_info, creation)),
      (long long)(offsetof(struct z_boot_info, parent_channel)),
      (long long)(offsetof(struct z_boot_info, template_id)),
      (long long)(offsetof(struct z_boot_info, depth)),
      (long long)(offsetof(struct z_boot_info, identity)),
      (long long)(offsetof(struct z_boot_info, reserved)),
      (long long)(sizeof(struct z_cap_request)),
      (long long)(_Alignof(struct z_cap_request)),
      (long long)(offsetof(struct z_cap_request, parent)),
      (long long)(offsetof(struct z_cap_request, holder)),
      (long long)(offsetof(struct z_cap_request, rights)),
      (long long)(offsetof(struct z_cap_request, reserved)),
      (long long)(sizeof(struct z_cap_info)),
      (long long)(_Alignof(struct z_cap_info)),
      (long long)(offsetof(struct z_cap_info, holder)),
      (long long)(offsetof(struct z_cap_info, target)),
      (long long)(offsetof(struct z_cap_info, rights)),
      (long long)(offsetof(struct z_cap_info, reserved)),
      (long long)(offsetof(struct z_cap_info, parent)),
      (long long)(sizeof(struct z_create_request)),
      (long long)(_Alignof(struct z_create_request)),
      (long long)(offsetof(struct z_create_request, authority)),
      (long long)(offsetof(struct z_create_request, request)),
      (long long)(offsetof(struct z_create_request, template_id)),
      (long long)(offsetof(struct z_create_request, descendant_slots)),
      (long long)(offsetof(struct z_create_request, descendant_pages)),
      (long long)(offsetof(struct z_create_request, reserved)),
      (long long)(sizeof(struct z_create_result)),
      (long long)(_Alignof(struct z_create_result)),
      (long long)(offsetof(struct z_create_result, instance)),
      (long long)(offsetof(struct z_create_result, control)),
      (long long)(offsetof(struct z_create_result, endpoint)),
      (long long)(offsetof(struct z_create_result, channel)),
      (long long)(offsetof(struct z_create_result, creation)),
      (long long)(offsetof(struct z_create_result, slot)),
      (long long)(offsetof(struct z_create_result, identity)),
      (long long)(sizeof(struct z_rebind_request)),
      (long long)(_Alignof(struct z_rebind_request)),
      (long long)(offsetof(struct z_rebind_request, authority)),
      (long long)(offsetof(struct z_rebind_request, control)),
      (long long)(offsetof(struct z_rebind_request, request)),
      (long long)(offsetof(struct z_rebind_request, reserved)),
      (long long)(sizeof(struct z_cell_status)),
      (long long)(_Alignof(struct z_cell_status)),
      (long long)(offsetof(struct z_cell_status, instance)),
      (long long)(offsetof(struct z_cell_status, control)),
      (long long)(offsetof(struct z_cell_status, endpoint)),
      (long long)(offsetof(struct z_cell_status, domain)),
      (long long)(offsetof(struct z_cell_status, parent_instance)),
      (long long)(offsetof(struct z_cell_status, parent_endpoint)),
      (long long)(offsetof(struct z_cell_status, generation)),
      (long long)(offsetof(struct z_cell_status, slot)),
      (long long)(offsetof(struct z_cell_status, template_id)),
      (long long)(offsetof(struct z_cell_status, depth)),
      (long long)(offsetof(struct z_cell_status, phase)),
      (long long)(offsetof(struct z_cell_status, faults)),
      (long long)(offsetof(struct z_cell_status, restarts)),
      (long long)(offsetof(struct z_cell_status, reason)),
      (long long)(offsetof(struct z_cell_status, own_pages)),
      (long long)(offsetof(struct z_cell_status, reserved_slots)),
      (long long)(offsetof(struct z_cell_status, reserved_pages)),
      (long long)(offsetof(struct z_cell_status, available_slots)),
      (long long)(offsetof(struct z_cell_status, available_pages)),
      (long long)(sizeof(struct z_domain_status)),
      (long long)(_Alignof(struct z_domain_status)),
      (long long)(offsetof(struct z_domain_status, domain)),
      (long long)(offsetof(struct z_domain_status, holder)),
      (long long)(offsetof(struct z_domain_status, instance)),
      (long long)(offsetof(struct z_domain_status, slot_limit)),
      (long long)(offsetof(struct z_domain_status, page_limit)),
      (long long)(offsetof(struct z_domain_status, owned_slots)),
      (long long)(offsetof(struct z_domain_status, owned_pages)),
      (long long)(offsetof(struct z_domain_status, reserved_slots)),
      (long long)(offsetof(struct z_domain_status, reserved_pages)),
      (long long)(offsetof(struct z_domain_status, available_slots)),
      (long long)(offsetof(struct z_domain_status, available_pages)),
      (long long)(offsetof(struct z_domain_status, max_depth)),
      (long long)(offsetof(struct z_domain_status, template_mask)),
      (long long)(offsetof(struct z_domain_status, recipe)),
      (long long)(offsetof(struct z_domain_status, revoked)));
}
'''


class LanguageLayoutTests(unittest.TestCase):
    def test_rust_wait_abi_constants_match(self):
        source = (ROOT / "policy/lib.rs").read_text()
        for rust_name, key in (("Z_ABI_VERSION", "version"), ("Z_SLEEP", "sleep"),
                               ("Z_RECV_WAIT", "recv_wait"), ("Z_TIMEOUT", "timeout"),
                               ("Z_WAIT_MAX_TICKS", "wait_max_ticks")):
            match = re.search(rf"pub const {rust_name}: \w+ = (-?\d+);", source)
            self.assertIsNotNone(match, rust_name)
            self.assertEqual(int(match.group(1)), EXPECTED[key], rust_name)

    def test_rust_storage_operation_constants_match(self):
        source = (ROOT / "policy/lib.rs").read_text()
        for rust_name, key in (("Z_OPERATION_MAX", "operation_max"),
                               ("Z_RIGHT_OPERATIONS", "operation_rights")):
            match = re.search(rf"pub const {rust_name}: \w+ = (\d+);", source)
            self.assertIsNotNone(match, rust_name)
            self.assertEqual(int(match.group(1)), EXPECTED[key], rust_name)

    def run_json(self, command):
        result = subprocess.run(command, cwd=ROOT, capture_output=True, text=True, timeout=20, check=True)
        return json.loads(result.stdout)

    def test_zig_and_c_layouts_match(self):
        zig = shlex.split(os.environ.get("ZIG", "zig"))
        actual_zig = self.run_json(zig + ["run", "cells/layout.zig"])
        self.assertEqual(actual_zig, EXPECTED)
        with tempfile.TemporaryDirectory() as directory:
            source = pathlib.Path(directory) / "abi.c"
            binary = pathlib.Path(directory) / "abi"
            source.write_text(C_SOURCE)
            cc = shlex.split(os.environ.get("CC", "cc"))
            subprocess.run(cc + ["-std=c11", "-Wall", "-Wextra", "-Werror", "-Iinclude",
                                 str(source), "-o", str(binary)], cwd=ROOT, timeout=20, check=True)
            self.assertEqual(self.run_json([str(binary)]), EXPECTED)


if __name__ == "__main__":
    unittest.main()
