const std = @import("std");
const abi = @import("abi.zig");

pub fn main() !void {
    var buffer: [8192]u8 = undefined;
    var used: usize = 0;
    used += (try std.fmt.bufPrint(buffer[used..],
        "{{\"version\":{d},\"find\":{d},\"delegate\":{d},\"query\":{d},\"revoke\":{d},\"no_space\":{d},\"timeout\":{d},\"wait_max_ticks\":{d},\"sleep\":{d},\"recv_wait\":{d},\"delegate_right\":{d},\"operation_max\":{d},\"operation_rights\":{d},\"instance_tag\":{d},\"control_tag\":{d},\"domain_tag\":{d},\"host_query_right\":{d},\"host_stop_right\":{d},\"host_reap_right\":{d},\"create\":{d},\"status\":{d},\"stop\":{d},\"reap\":{d},\"rebind\":{d},",
        .{
            abi.version,
            @intFromEnum(abi.Call.find),
            @intFromEnum(abi.Call.delegate),
            @intFromEnum(abi.Call.query),
            @intFromEnum(abi.Call.revoke),
            @intFromEnum(abi.Error.no_space),
            @intFromEnum(abi.Error.timeout),
            abi.wait_max_ticks,
            @intFromEnum(abi.Call.sleep),
            @intFromEnum(abi.Call.recv_wait),
            abi.delegate_right,
            @intFromEnum(abi.Operation.hosting_reply),
            abi.operation_rights,
            abi.instance_tag,
            abi.control_tag,
            abi.domain_tag,
            abi.host_query_right,
            abi.host_stop_right,
            abi.host_reap_right,
            @intFromEnum(abi.Call.create),
            @intFromEnum(abi.Call.status),
            @intFromEnum(abi.Call.stop),
            @intFromEnum(abi.Call.reap),
            @intFromEnum(abi.Call.rebind),
        })).len;
    used += (try std.fmt.bufPrint(buffer[used..],
        "\"creation_revoke\":{d},\"domain_status\":{d},\"file_read_right\":{d},\"cap_ack_right\":{d},\"block_read_right\":{d},\"block_write_right\":{d},\"block_reply_right\":{d},\"file_open_right\":{d},\"file_chunk_read_right\":{d},\"file_write_right\":{d},\"file_close_right\":{d},\"file_result_right\":{d},\"hosting_request_right\":{d},\"hosting_reply_right\":{d},\"role_block\":{d},\"role_filesystem\":{d},\"role_client\":{d},\"role_probe\":{d},\"role_supervisor\":{d},\"role_worker\":{d},\"message_size\":{d},\"message_align\":{d},\"message_sender\":{d},\"message_operation\":{d},",
        .{
            @intFromEnum(abi.Call.creation_revoke),
            @intFromEnum(abi.Call.domain_status),
            abi.right(.file_read),
            abi.right(.cap_ack),
            abi.right(.block_read),
            abi.right(.block_write),
            abi.right(.block_reply),
            abi.right(.file_open),
            abi.right(.file_chunk_read),
            abi.right(.file_write),
            abi.right(.file_close),
            abi.right(.file_result),
            abi.right(.hosting_request),
            abi.right(.hosting_reply),
            @intFromEnum(abi.Role.block),
            @intFromEnum(abi.Role.filesystem),
            @intFromEnum(abi.Role.client),
            @intFromEnum(abi.Role.probe),
            @intFromEnum(abi.Role.supervisor),
            @intFromEnum(abi.Role.worker),
            @sizeOf(abi.Message),
            @alignOf(abi.Message),
            @offsetOf(abi.Message, "sender"),
            @offsetOf(abi.Message, "operation"),
        })).len;
    used += (try std.fmt.bufPrint(buffer[used..],
        "\"message_length\":{d},\"message_payload\":{d},\"boot_size\":{d},\"boot_align\":{d},\"boot_abi\":{d},\"boot_role\":{d},\"boot_generation\":{d},\"boot_scenario\":{d},\"boot_endpoint\":{d},\"boot_parent_endpoint\":{d},\"boot_instance\":{d},\"boot_creation\":{d},\"boot_parent_channel\":{d},\"boot_template_id\":{d},\"boot_depth\":{d},\"boot_identity\":{d},\"boot_reserved\":{d},\"request_size\":{d},\"request_align\":{d},\"request_parent\":{d},\"request_holder\":{d},\"request_rights\":{d},\"request_reserved\":{d},\"info_size\":{d},",
        .{
            @offsetOf(abi.Message, "length"),
            @offsetOf(abi.Message, "payload"),
            @sizeOf(abi.BootInfo),
            @alignOf(abi.BootInfo),
            @offsetOf(abi.BootInfo, "abi"),
            @offsetOf(abi.BootInfo, "role"),
            @offsetOf(abi.BootInfo, "generation"),
            @offsetOf(abi.BootInfo, "scenario"),
            @offsetOf(abi.BootInfo, "endpoint"),
            @offsetOf(abi.BootInfo, "parent_endpoint"),
            @offsetOf(abi.BootInfo, "instance"),
            @offsetOf(abi.BootInfo, "creation"),
            @offsetOf(abi.BootInfo, "parent_channel"),
            @offsetOf(abi.BootInfo, "template_id"),
            @offsetOf(abi.BootInfo, "depth"),
            @offsetOf(abi.BootInfo, "identity"),
            @offsetOf(abi.BootInfo, "reserved"),
            @sizeOf(abi.DelegateRequest),
            @alignOf(abi.DelegateRequest),
            @offsetOf(abi.DelegateRequest, "parent"),
            @offsetOf(abi.DelegateRequest, "holder_endpoint"),
            @offsetOf(abi.DelegateRequest, "rights"),
            @offsetOf(abi.DelegateRequest, "reserved"),
            @sizeOf(abi.CapabilityInfo),
        })).len;
    used += (try std.fmt.bufPrint(buffer[used..],
        "\"info_align\":{d},\"info_holder\":{d},\"info_target\":{d},\"info_rights\":{d},\"info_reserved\":{d},\"info_parent\":{d},\"create_request_size\":{d},\"create_request_align\":{d},\"create_request_authority\":{d},\"create_request_request\":{d},\"create_request_template_id\":{d},\"create_request_descendant_slots\":{d},\"create_request_descendant_pages\":{d},\"create_request_reserved\":{d},\"create_result_size\":{d},\"create_result_align\":{d},\"create_result_instance\":{d},\"create_result_control\":{d},\"create_result_endpoint\":{d},\"create_result_channel\":{d},\"create_result_creation\":{d},\"create_result_slot\":{d},\"create_result_identity\":{d},\"rebind_request_size\":{d},",
        .{
            @alignOf(abi.CapabilityInfo),
            @offsetOf(abi.CapabilityInfo, "holder"),
            @offsetOf(abi.CapabilityInfo, "target"),
            @offsetOf(abi.CapabilityInfo, "rights"),
            @offsetOf(abi.CapabilityInfo, "reserved"),
            @offsetOf(abi.CapabilityInfo, "parent"),
            @sizeOf(abi.CreateRequest),
            @alignOf(abi.CreateRequest),
            @offsetOf(abi.CreateRequest, "authority"),
            @offsetOf(abi.CreateRequest, "request"),
            @offsetOf(abi.CreateRequest, "template_id"),
            @offsetOf(abi.CreateRequest, "descendant_slots"),
            @offsetOf(abi.CreateRequest, "descendant_pages"),
            @offsetOf(abi.CreateRequest, "reserved"),
            @sizeOf(abi.CreateResult),
            @alignOf(abi.CreateResult),
            @offsetOf(abi.CreateResult, "instance"),
            @offsetOf(abi.CreateResult, "control"),
            @offsetOf(abi.CreateResult, "endpoint"),
            @offsetOf(abi.CreateResult, "channel"),
            @offsetOf(abi.CreateResult, "creation"),
            @offsetOf(abi.CreateResult, "slot"),
            @offsetOf(abi.CreateResult, "identity"),
            @sizeOf(abi.RebindRequest),
        })).len;
    used += (try std.fmt.bufPrint(buffer[used..],
        "\"rebind_request_align\":{d},\"rebind_request_authority\":{d},\"rebind_request_control\":{d},\"rebind_request_request\":{d},\"rebind_request_reserved\":{d},\"cell_status_size\":{d},\"cell_status_align\":{d},\"cell_status_instance\":{d},\"cell_status_control\":{d},\"cell_status_endpoint\":{d},\"cell_status_domain\":{d},\"cell_status_parent_instance\":{d},\"cell_status_parent_endpoint\":{d},\"cell_status_generation\":{d},\"cell_status_slot\":{d},\"cell_status_template_id\":{d},\"cell_status_depth\":{d},\"cell_status_phase\":{d},\"cell_status_faults\":{d},\"cell_status_restarts\":{d},\"cell_status_reason\":{d},\"cell_status_own_pages\":{d},\"cell_status_reserved_slots\":{d},\"cell_status_reserved_pages\":{d},",
        .{
            @alignOf(abi.RebindRequest),
            @offsetOf(abi.RebindRequest, "authority"),
            @offsetOf(abi.RebindRequest, "control"),
            @offsetOf(abi.RebindRequest, "request"),
            @offsetOf(abi.RebindRequest, "reserved"),
            @sizeOf(abi.CellStatus),
            @alignOf(abi.CellStatus),
            @offsetOf(abi.CellStatus, "instance"),
            @offsetOf(abi.CellStatus, "control"),
            @offsetOf(abi.CellStatus, "endpoint"),
            @offsetOf(abi.CellStatus, "domain"),
            @offsetOf(abi.CellStatus, "parent_instance"),
            @offsetOf(abi.CellStatus, "parent_endpoint"),
            @offsetOf(abi.CellStatus, "generation"),
            @offsetOf(abi.CellStatus, "slot"),
            @offsetOf(abi.CellStatus, "template_id"),
            @offsetOf(abi.CellStatus, "depth"),
            @offsetOf(abi.CellStatus, "phase"),
            @offsetOf(abi.CellStatus, "faults"),
            @offsetOf(abi.CellStatus, "restarts"),
            @offsetOf(abi.CellStatus, "reason"),
            @offsetOf(abi.CellStatus, "own_pages"),
            @offsetOf(abi.CellStatus, "reserved_slots"),
            @offsetOf(abi.CellStatus, "reserved_pages"),
        })).len;
    used += (try std.fmt.bufPrint(buffer[used..],
        "\"cell_status_available_slots\":{d},\"cell_status_available_pages\":{d},\"domain_status_size\":{d},\"domain_status_align\":{d},\"domain_status_domain\":{d},\"domain_status_holder\":{d},\"domain_status_instance\":{d},\"domain_status_slot_limit\":{d},\"domain_status_page_limit\":{d},\"domain_status_owned_slots\":{d},\"domain_status_owned_pages\":{d},\"domain_status_reserved_slots\":{d},\"domain_status_reserved_pages\":{d},\"domain_status_available_slots\":{d},\"domain_status_available_pages\":{d},\"domain_status_max_depth\":{d},\"domain_status_template_mask\":{d},\"domain_status_recipe\":{d},\"domain_status_revoked\":{d}}}\n",
        .{
            @offsetOf(abi.CellStatus, "available_slots"),
            @offsetOf(abi.CellStatus, "available_pages"),
            @sizeOf(abi.DomainStatus),
            @alignOf(abi.DomainStatus),
            @offsetOf(abi.DomainStatus, "domain"),
            @offsetOf(abi.DomainStatus, "holder"),
            @offsetOf(abi.DomainStatus, "instance"),
            @offsetOf(abi.DomainStatus, "slot_limit"),
            @offsetOf(abi.DomainStatus, "page_limit"),
            @offsetOf(abi.DomainStatus, "owned_slots"),
            @offsetOf(abi.DomainStatus, "owned_pages"),
            @offsetOf(abi.DomainStatus, "reserved_slots"),
            @offsetOf(abi.DomainStatus, "reserved_pages"),
            @offsetOf(abi.DomainStatus, "available_slots"),
            @offsetOf(abi.DomainStatus, "available_pages"),
            @offsetOf(abi.DomainStatus, "max_depth"),
            @offsetOf(abi.DomainStatus, "template_mask"),
            @offsetOf(abi.DomainStatus, "recipe"),
            @offsetOf(abi.DomainStatus, "revoked"),
        })).len;
    const output = buffer[0..used];
    var offset: usize = 0;
    while (offset < output.len) offset += try std.posix.write(1, output[offset..]);
}
